### ISSUE TITLE
bookingManagerSend not found

### ISSUE THREAD

**Issue by laurent-d** [acrontum/kirby-booking-manager-plugin#1]
Hi,

Thanks for your awesome work with this plugin.
When i try to use your script on submit i have an error 302 : page not found with a call page bookingManagerSend.
It's a configuration server issue or this page is available ? Not found in your git.

Laurent

**Comment by mbrode** [comment]
Hi Laurent, 

we will have a look on this issue and reply you as soon as possible. 

Cheers,
Michael

**Comment by Acrontum-Carmichael** [comment]
Hi Laurent,

I have just tried to replicate your issue with a fresh install of the default templates from the booking manager but could not see a 302 redirect.

Could I ask if you have used your own templates and if so what they might look like?

Kind regards,
John

**Comment by laurent-d** [comment]
Hi John,

No i use the starter template, a pure clean install.
How the form submit the booking informations ?
My install is here http://avant-garde.io/kirby/booking-manager
Please see the screenshot attached.

It's possibly a miss-configuration server.. ?
![manager-send](https://cloud.githubusercontent.com/assets/6553086/11633591/6d9c092a-9d0c-11e5-821f-c53e42b3014f.gif)

Laurent

**Comment by Acrontum-Carmichael** [comment]
Hi Laurent,

I can see the action of the form is routing to `/kirby/bookingManagerSend`. I will check to see if the plugin can handle routing any deeper than the route of the domain, eg in your case: `avant-garde.io/bookingManagerSend`.

Kind regards,
John

**Comment by Acrontum-Carmichael** [comment]
Hi Laurent,

I have tried running the Kirby CMS one folder deep from the Apache document root but still cannot replicate your issue.

Here is a snapshot of the network tab from the console.
![capture](https://cloud.githubusercontent.com/assets/16192806/11634783/e27dbc42-9d12-11e5-803b-9e54021c55cc.PNG)

This is a snapshot of the file set from the site, which is a direct pull from this git repository.
![capture](https://cloud.githubusercontent.com/assets/16192806/11634844/3c13d9ee-9d13-11e5-9d6a-1025c283f5dd.PNG)

Kind regards,
John

**Comment by laurent-d** [comment]
The file sendBookingMail.php is missing in my install and in the Git..

**Comment by Acrontum-Carmichael** [comment]
Hi Laurent,

Thank you making us aware of this issue, this somehow got overlooked. The issue has now been fixed and more sample content provided with the plugin.

Kind regards,
John

**Comment by laurent-d** [comment]
John it's perfect +1: 

Have just others little issues :
- The Booking request is from info@acrontum.de, can i configure it ?
  and what is the goal of bookingManagerApprove?booker=... link ?

Thank you so much for your first class support

**Comment by Acrontum-Carmichael** [comment]
Hi Laurent, 

You should be able to configure this from the site.txt file in the content folder, or in the kirby panel (which reads the site.txt file.

Glad to have helped. As this is now all fixed I will close the ticket.

Regards,
John
